name: Build Mod
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Unzip project
        run: unzip -o "ahsell-mod (1).zip" -d .
      - name: Generate Gradle Wrapper
        run: gradle wrapper
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Built-Mod-Jar
          path: build/libs/*.jar
